version: '3'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
# Uncomment for DHCP
     # - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: Europe/Prague
      WEBPASSWORD: ${PIHOLE_PWD}
      DNS1: ${UNBOUND_IP}#53
      DNS2: 'no'
    volumes:
       - ./etc-pihole/:/etc/pihole/
       - ./etc-dnsmasq.d/:/etc/dnsmasq.d/
    dns:
      - 127.0.0.1
      - ${DNS_IP}
    networks:
        - pinet
    restart: always
  unbound:
    container_name: unbound
#    build: ./unbound/
    image: artee666/unbound
    hostname: unbound
    networks:
        pinet:
            ipv4_address: ${UNBOUND_IP}
    restart: always

networks:
    pinet:
        driver: bridge
        ipam:
            config:
                - subnet: ${PINET_SUBNET}
